#!/usr/bin/env bash
# Nginx reverse proxy for Case Management Platform (path-based hosting).
#
#   sudo bash deploy/configure-nginx.sh
#
# Writes /etc/nginx/sites-available/<PUBLIC_HOST> when PUBLIC_HOST is set.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/deploy/.env}"

run_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

load_env_file() {
  local file=$1
  [[ -f "$file" ]] || return 1
  local line key value
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line//$'\r'/}"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      key="${BASH_REMATCH[1]}"
      value="${BASH_REMATCH[2]}"
      value="${value#\"}"; value="${value%\"}"
      value="${value#\'}"; value="${value%\'}"
      export "$key=$value"
    fi
  done < "$file"
  return 0
}

normalize_path() {
  local value="${1:-}"
  value="/${value#/}"
  echo "${value%/}"
}

write_site() {
  local host=$1 cert=$2 key=$3 base_path=$4 app_port=$5
  cat <<EOF
# Generated by deploy/configure-nginx.sh — recreate with: sudo bash deploy/configure-nginx.sh

server {
    listen 80;
    server_name ${host};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    server_name ${host};
    client_max_body_size 12m;
    ssl_certificate ${cert};
    ssl_certificate_key ${key};

    add_header X-Content-Type-Options nosniff;

    location = ${base_path} {
        return 301 ${base_path}/;
    }

    location ${base_path}/ {
        proxy_pass http://127.0.0.1:${app_port}${base_path}/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF
}

main() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Skip nginx: missing $ENV_FILE (set PUBLIC_HOST and SSL paths first)." >&2
    exit 0
  fi
  load_env_file "$ENV_FILE"
  # shellcheck source=deploy/public-host.sh
  source "$ROOT/deploy/public-host.sh"
  resolve_public_urls

  local host="${PUBLIC_HOST:-}"
  if [[ -z "$host" ]]; then
    echo "Skip nginx: PUBLIC_HOST not set in $ENV_FILE" >&2
    exit 0
  fi

  local base_path
  base_path="$(normalize_path "${APP_BASE_PATH:-/case-management}")"
  local app_port="${APP_PORT:-4510}"
  local cert="${SSL_CERTIFICATE:-/etc/ssl/certs/ssl-cert-snakeoil.pem}"
  local key="${SSL_CERTIFICATE_KEY:-/etc/ssl/private/ssl-cert-snakeoil.key}"

  if [[ ! -f "$cert" || ! -f "$key" ]]; then
    echo "Skip nginx: SSL certificate files not found:" >&2
    echo "  SSL_CERTIFICATE=$cert" >&2
    echo "  SSL_CERTIFICATE_KEY=$key" >&2
    exit 0
  fi

  if ! command -v nginx >/dev/null 2>&1; then
    echo "==> Installing nginx..."
    run_root apt-get update
    run_root apt-get install -y nginx
  fi

  local site="/etc/nginx/sites-available/${host}"
  local enabled="/etc/nginx/sites-enabled/${host}"
  echo "==> Writing ${site}"
  write_site "$host" "$cert" "$key" "$base_path" "$app_port" | run_root tee "$site" >/dev/null
  run_root ln -sf "$site" "$enabled"
  run_root rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
  run_root nginx -t
  run_root systemctl reload nginx
  echo "==> nginx reloaded for https://${host}${base_path}/"
}

main "$@"
