#!/usr/bin/env bash
# Nginx for Case Management Platform on a shared demo host (client-demo.inapp.com).
#
# Primary: write /etc/nginx/snippets/case-management.conf and include it in the
# existing listen 443 server for PUBLIC_HOST (same pattern as FWA / PM2 runbook).
# Does not replace location / or /api/ owned by other apps.
#
# Fallback: if no vhost exists for PUBLIC_HOST, write a dedicated site that
# only includes the snippet.
#
#   sudo bash deploy/configure-nginx.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/deploy/.env}"

run_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

load_env_file() {
  local file=$1
  [[ -f "$file" ]] || return 1
  local line key value
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line//$'\r'/}"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      key="${BASH_REMATCH[1]}"
      value="${BASH_REMATCH[2]}"
      value="${value#\"}"; value="${value%\"}"
      value="${value#\'}"; value="${value%\'}"
      export "$key=$value"
    fi
  done < "$file"
  return 0
}

normalize_path() {
  local value="${1:-}"
  value="/${value#/}"
  echo "${value%/}"
}

write_snippet() {
  local base_path=$1 app_port=$2
  cat <<EOF
# Generated by deploy/configure-nginx.sh — Case Management Platform
# include this file inside the existing listen 443 server for ${PUBLIC_HOST}.
# Do not replace location / or location /api/.

location = ${base_path} {
    return 301 ${base_path}/;
}

location ${base_path}/ {
    proxy_pass http://127.0.0.1:${app_port}${base_path}/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_cache_bypass \$http_upgrade;
    proxy_read_timeout 120s;
    proxy_send_timeout 120s;
    client_max_body_size 12m;
}
EOF
}

find_vhost() {
  local host=$1
  local dir f
  for dir in /etc/nginx/sites-enabled /etc/nginx/sites-available /etc/nginx/conf.d; do
    [[ -d "$dir" ]] || continue
    for f in "$dir"/*; do
      [[ -f "$f" || -L "$f" ]] || continue
      if grep -q "server_name[^;]*${host}" "$f" 2>/dev/null; then
        echo "$f"
        return 0
      fi
    done
  done
  return 1
}

insert_include() {
  local vhost=$1 include_line=$2
  if grep -qF "$SNIPPET" "$vhost"; then
    echo "    Include already present in $vhost"
    return 0
  fi
  echo "==> Inserting ${include_line} into ${vhost}"
  EDIT_TMP="$(mktemp)"
  cp "$vhost" "$EDIT_TMP"
  python3 - "$EDIT_TMP" "$include_line" <<'PY'
import sys
path, include = sys.argv[1], sys.argv[2]
text = open(path, encoding="utf-8", errors="replace").read()
needle = "listen 443"
idx = text.find(needle)
if idx == -1:
    print("Warning: no listen 443 in vhost; append include at end of first server", file=sys.stderr)
    idx = text.find("server {")
if idx == -1:
    sys.exit("no server block found")
depth = 0
started = False
insert_at = None
i = text.rfind("server", 0, idx)
if i == -1:
    i = idx
while i < len(text):
    if text[i] == "{":
        depth += 1
        started = True
    elif text[i] == "}":
        depth -= 1
        if started and depth == 0:
            insert_at = i
            break
    i += 1
if insert_at is None:
    sys.exit("could not find server close brace")
updated = text[:insert_at] + f"    {include}\n" + text[insert_at:]
open(path, "w", encoding="utf-8").write(updated)
PY
  run_root cp "$EDIT_TMP" "$vhost"
  rm -f "$EDIT_TMP"
}

main() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Error: missing $ENV_FILE — run bash start.sh first or copy deploy/.env.example." >&2
    exit 1
  fi
  load_env_file "$ENV_FILE"
  # shellcheck source=deploy/public-host.sh
  source "$ROOT/deploy/public-host.sh"
  resolve_public_urls

  PUBLIC_HOST="${PUBLIC_HOST#https://}"
  PUBLIC_HOST="${PUBLIC_HOST#http://}"
  PUBLIC_HOST="${PUBLIC_HOST%/}"
  PUBLIC_HOST="${PUBLIC_HOST:-client-demo.inapp.com}"

  local base_path app_port
  base_path="$(normalize_path "${APP_BASE_PATH:-/case-management}")"
  app_port="${APP_PORT:-4510}"
  SNIPPET="${NGINX_SNIPPET:-/etc/nginx/snippets/case-management.conf}"
  SSL_CERTIFICATE="${SSL_CERTIFICATE:-/etc/ssl/inapp/SSL/inapp.com.pem}"
  SSL_CERTIFICATE_KEY="${SSL_CERTIFICATE_KEY:-/etc/ssl/inapp/SSL/inapp.com.key}"

  echo "==> Writing nginx snippet ${SNIPPET}"
  echo "    Host : ${PUBLIC_HOST}"
  echo "    App  : 127.0.0.1:${app_port}${base_path}/"

  if ! command -v nginx >/dev/null 2>&1; then
    if ! command -v apt-get >/dev/null 2>&1; then
      echo "Error: nginx is not installed and apt-get is not available." >&2
      exit 1
    fi
    echo "==> Installing nginx..."
    run_root apt-get update -y
    run_root apt-get install -y nginx
  fi

  TMP="$(mktemp)"
  write_snippet "$base_path" "$app_port" >"$TMP"
  run_root mkdir -p "$(dirname "$SNIPPET")"
  run_root cp "$TMP" "$SNIPPET"
  rm -f "$TMP"

  local include_line="include ${SNIPPET};"
  local vhost=""
  if vhost="$(find_vhost "$PUBLIC_HOST")"; then
    echo "    Vhost: $vhost"
    insert_include "$vhost" "$include_line"
  else
    echo "==> No existing vhost for ${PUBLIC_HOST} — writing a dedicated site"
    if [[ ! -f "$SSL_CERTIFICATE" || ! -f "$SSL_CERTIFICATE_KEY" ]]; then
      echo "Error: SSL files not found:" >&2
      echo "  SSL_CERTIFICATE=$SSL_CERTIFICATE" >&2
      echo "  SSL_CERTIFICATE_KEY=$SSL_CERTIFICATE_KEY" >&2
      exit 1
    fi
    SITE_TMP="$(mktemp)"
    cat >"$SITE_TMP" <<EOF
# Generated by deploy/configure-nginx.sh
server {
    listen 80;
    server_name ${PUBLIC_HOST};
    return 301 https://\$host\$request_uri;
}
server {
    listen 443 ssl;
    server_name ${PUBLIC_HOST};
    ssl_certificate ${SSL_CERTIFICATE};
    ssl_certificate_key ${SSL_CERTIFICATE_KEY};
    client_max_body_size 12m;
    add_header X-Content-Type-Options nosniff;
    ${include_line}
}
EOF
    if [[ -d /etc/nginx/sites-available ]]; then
      run_root cp "$SITE_TMP" "/etc/nginx/sites-available/${PUBLIC_HOST}"
      run_root ln -sfn "/etc/nginx/sites-available/${PUBLIC_HOST}" "/etc/nginx/sites-enabled/${PUBLIC_HOST}"
    else
      run_root mkdir -p /etc/nginx/conf.d
      run_root cp "$SITE_TMP" "/etc/nginx/conf.d/case-management.conf"
    fi
    rm -f "$SITE_TMP"
    run_root rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
  fi

  echo "==> Testing nginx configuration..."
  if ! run_root nginx -t; then
    echo "Error: nginx -t failed." >&2
    exit 1
  fi

  if command -v systemctl >/dev/null 2>&1; then
    run_root systemctl enable nginx >/dev/null 2>&1 || true
    if run_root systemctl is-active --quiet nginx; then
      run_root systemctl reload nginx
    else
      run_root systemctl start nginx
    fi
  else
    run_root nginx -s reload 2>/dev/null || run_root nginx
  fi

  echo ""
  echo "Nginx snippet installed:"
  echo "  App : https://${PUBLIC_HOST}${base_path}/"
  echo "  API : https://${PUBLIC_HOST}${base_path}/api"
  echo ""
  echo "Re-run: sudo bash $ROOT/deploy/configure-nginx.sh"
}

main "$@"
